### ISSUE TITLE
License plate issue

### ISSUE THREAD

**Issue by Leny1337** [Whitetigerswt/samp-font-changer#5]
Before using sampfont:
![sa-mp-223](https://cloud.githubusercontent.com/assets/8152038/3565709/7007c5b6-0acb-11e4-97fc-8c22014ec39e.png)

And after:
![sa-mp-224](https://cloud.githubusercontent.com/assets/8152038/3565712/77c5fc28-0acb-11e4-809f-cebdb7462964.png)

**Comment by Whitetigerswt** [comment]
I'll have to look into this

**Comment by Leny1337** [comment]
And? Have you looked into it?
